name: Bala Woodlands Tent and Trailer Campgroud
favicon: null
layout_spectrum: 0.6450961034279317
typography_spectrum: 0.9653196330182254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4132472164928913
  lightness: 0.37673815386369824
  saturation: 0.9973170426674187
  rhythmicContrast: 0.032035196432843804
purpose: []
