name: Bala Woodlands
favicon: null
layout_spectrum: 0.59231
typography_spectrum: 0.50905
title: Bala Woodlands Tent and Trailer Campgroud
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0b4cd'
    - '#c74800'
    - '#4e352a'
    - '#5c0000'
    - '#f4e3d9'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
