name: Bala Woodlands Tent and Trailer Campgroud
favicon: null
layout_spectrum: 0.37251
typography_spectrum: 0.50115
title: Bala Woodlands Tent and Trailer Campgroud
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060405'
    - '#57627e'
    - '#2c3b52'
    - '#798697'
    - '#b9b9b7'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
